name: create release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get pushed tag
        id: get_pushed_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - uses: actions/checkout@v3

      - run: git archive --output=bazoku-${{ steps.get_pushed_tag.outputs.TAG }}.tar.gz ${{ steps.get_pushed_tag.outputs.TAG }}

      - name: get SHA256 of archive
        id: get_sha
        run: echo "::set-output name=sha::$(sha256sum bazoku-${{ steps.get_pushed_tag.outputs.TAG }}.tar.gz | cut -f 1 -d ' ')"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ```
            http_archive(
                name = "bazoku",
                sha256 = "${{ steps.get_sha.outputs.sha }}",
                urls = ["https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/releases/download/${{ steps.get_pushed_tag.outputs.TAG }}/bazoku-${{ steps.get_pushed_tag.outputs.TAG }}.tar.gz"],
            )
            ```
          generate_release_notes: true
          files: bazoku-${{ steps.get_pushed_tag.outputs.TAG }}.tar.gz
